# Generated by Django 6.0.6 on 2026-06-08 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('comida', 'Comida'), ('cena', 'Cena')], max_length=10)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='pm_app.comida')),
            ],
            options={
                'unique_together': {('dia', 'tipo_comida')},
            },
        ),
    ]
